services:
    postgres:
        image: postgres:17
        restart: on-failure
        environment:
            POSTGRES_USER: kpo
            POSTGRES_PASSWORD: password
            POSTGRES_DB: kpo
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    rabbitmq:
        pull_policy: missing
        image: rabbitmq:4.0.6-management-alpine
        restart: on-failure
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password


    order-service:
        hostname: order
        image: order-service:1.0-SNAPSHOT
        environment: &environment
            SPRING_PROFILES_ACTIVE: docker
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kpo
            SERVER_ADDRESS: 0.0.0.0

        depends_on: [ postgres, rabbitmq ]
        working_dir: /app/modules/orders

    payment-service:
        hostname: payment
        image: payments-service:1.0-SNAPSHOT
        environment: *environment
        depends_on: [ postgres, rabbitmq ]
        ports: [ "8082:8080" ]
        working_dir: /app/modules/payments

    nginx:
        image: nginx:latest
        restart: on-failure
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on: [ order-service, payment-service ]

volumes:
    postgres-data:
        driver: local
    rabbitmq_data:
        driver: local
    redis_data:
        driver: local
