spring:
    application.name: order-service
    datasource:
        url: jdbc:postgresql://${DB_HOST:-postgres}:5432/kpo
        username: kpo
        password: password
    jpa:
        hibernate.ddl-auto: validate      # schema через Flyway
        properties.hibernate.format_sql: true
    rabbitmq:
        host: rabbitmq
        port: 5672
logging.level.org.springframework.amqp: WARN